app:
    resource: '@AppBundle/Controller/'
    type: annotation

movies:
  type: rest
  resource: AppBundle\Controller\MoviesController

movies_post:
  path: /movies
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\MoviesController:postMoviesAction
    _format: json

human:
  type: rest
  resource: AppBundle\Controller\HumanController

human_post:
  path: /humans
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\HumanController:postHumansAction
    _format: json

movies_roles_post:
  path: /movies/{movie}/roles
  methods: [POST]
  defaults:
    _controller: AppBundle\Controller\MoviesController:postMovieRolesAction
    _format: json
